<<<<<<< HEAD
# Generated by Django 3.0.2 on 2020-01-21 05:57
=======
# Generated by Django 3.0.2 on 2020-01-22 18:22
>>>>>>> 58c8965ffe909912e9d7c91aaf00cc3c1509b4b9

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Tutorial',
=======
            name='Tutorials',
>>>>>>> 58c8965ffe909912e9d7c91aaf00cc3c1509b4b9
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_title', models.CharField(max_length=200)),
                ('tutorial_content', models.TextField()),
<<<<<<< HEAD
                ('tutorial_publish', models.DateTimeField(verbose_name='date published')),
=======
                ('tutorial_published', models.DateTimeField(verbose_name='Published Date')),
>>>>>>> 58c8965ffe909912e9d7c91aaf00cc3c1509b4b9
            ],
        ),
    ]
