# Generated by Django 3.0.2 on 2020-01-29 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorials',
            options={'verbose_name_plural': 'Tutorials'},
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 18, 32, 9, 669548), verbose_name='Published Date'),
        ),
    ]
