# Generated by Django 3.0.2 on 2020-01-29 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 29, 14, 40, 19, 284089), verbose_name='Published Date'),
        ),
    ]
