# Generated by Django 3.0.2 on 2020-01-30 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200129_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 13, 42, 11, 411061), verbose_name='Published Date'),
        ),
    ]
